### ISSUE TITLE
CTAN outdated

### ISSUE THREAD

**Issue by Mythologyli** [zjulug/mirrors-issue-tracker#32]
It seems that it has not been updated after 2020.

**Comment by vxst** [comment]
We have just upgraded our infrastructure and started to sync with upstreams.

Since exposing partially synced distros will break the upgrade process, we will only expose the latest version for the distro after the syncing process is fully completed (which also includes CTAN).

We will announce the news on this issue once the sync process for CTAN is completed.

Thank you for your support.
